version: "3.9"
services:
    web:
        build: .
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__ApplicationConnectionString=Server=db;Initial Catalog=ArticlesDb;User ID=sa;Password=123456789Qw!;Connection Timeout=240;
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "123456789Qw!"
            ACCEPT_EULA: "Y"